#设置项目名
server:
  port: 28083

nacosIp: 150.158.121.165

spring:
  application:
    name: nacos-demo-boot

nacos:
  discovery:
    serverAddr: ${nacosIp}:8848
  config:
    serverAddr: ${nacosIp}:8848
    namespace: springBootAgg
    group: nacosDemo
    dataId: ${spring.application.name}.yml
    type: yaml
    auto-refresh: true
    ext-config:
      - dataId: ${spring.application.name}-ext.yml
        server-addr: ${nacosIp}:8848
        namespace: springBootAgg
        group: nacosDemo
        type: yaml
        autoRefresh: true




## 设置项目名
#server.port=28083
#
#nacosIp=150.158.121.165
#
#spring.application.name=nacos-demo-boot
#
#nacos.discovery.sever-addr=${nacosIp}:8848
#nacos.config.server-addr=${nacosIp}:8848
#nacos.config.namespace=springBootAgg
##nacos.config.group=nacosDemo
##nacos.config.dataId=${spring.application.name}.yml
##nacos.config.auto-refresh=true
##nacos.config.ext-config[0].dataId=${spring.application.name}-ext.yml
##nacos.config.ext-config[0].server-addr=${nacosIp}:8848
##nacos.config.ext-config[0].namespace=springBootAgg
##nacos.config.ext-config[0].group=nacosDemo
##nacos.config.ext-config[0].autoRefresh=true

