extraEnvHost: hujingzheng.com

spring:
  application:
    name: base-project
  #===============数据库=================
  #spring-boot中对于@RestController或者@Controller+@ResponseBody注解的接口方法的返回值默认是Json格式，
  #对于date类型的数据，在返回浏览器端是会被spring-boot默认的Jackson框架转换，而Jackson框架默认的时区GMT（相对于中国是少了8小时）
  jackson:
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://${extraEnvHost}:3306/springBootDemo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&rewriteBatchedStatements=true
    username: ${jdbc.username}
    password: ${jdbc.pwd}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${extraEnvHost}
      port: 6379
      password: ${redis.pwd}
  cloud:
    nacos:
      config:
        server-addr: ${extraEnvHost}:38080
        group: DEFAULT_GROUP
        file-extension: properties
      discovery:
        server-addr: ${extraEnvHost}:38080
  config:
    import:
      - optional:nacos:base-project