#设置项目名
server:
  servlet:
    context-path: /nacos-provider2   #设置应用访问url的名字
  port: 28084

nacosServerHost: 212.64.18.166

spring:
  application:
    name: nacos-provider  #设置应用的名字
  cloud:
    nacos:
      discovery:
        server-addr: ${nacosServerHost}:30000
        #注意:配置group的时候,必须配置一个namespace(这个值是从nacos控制台命名空间获取的ID值),这样才能设置权重和负载均衡
        namespace: rrrrrrrrr
        cluster-name: kkk






