spring:
  application:
    name: dubbo-provider

server:
  port: 8082

serverHost: 150.158.121.165

dubbo:
  application:
    name: dubbo-consumer-dubbo
    qos-port: 33334
    auto-trust-serialize-class: true
    #从前往后数的(默认值是3)
    trustSerializeClassLevel: 3
  protocol:
    name: dubbo
    port: 20885
  registry:
    address: nacos://${serverHost}:8848
    registerMode: instance
#    register: false
    #对应的分组名称
    group: DEFAULT_GROUP
    #对应的命名空间
    parameters:
      namespace: springBootAgg
  consumer:
    #启动不在是否有提供者,默认true如果没有则终止进程
    check: true
    #服务端如果返回超时(默认是1秒)会自动重试(默认是2秒)
    retries: 0

