
server:
  port: 8080

extraEnvHost: 212.64.18.166


app:
  id: shardingJDBC
apollo:
  meta: http://${extraEnvHost}:8080
  bootstrap:
    namespaces: application,common-mysql
    enabled: true
    eagerLoad:
      enabled: false


spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        #注意如果选择druid的连接池,需要换成字段jdbc-url为url
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${extraEnvHost}:3306/sharding?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&rewriteBatchedStatements=true
        username: ${jdbc.username}
        password: ${jdbc.pwd}
    sharding:
      tables:
        suser_sharding:
          actual-data-nodes: ds0.suser_sharding_$->{0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: suser_sharding_$->{id % 2}
          key-generator:
            column: id
            type: SNOWFLAKE
    props:
      sql:
        show: true


#MyBatis-Plus的相关配置
mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO





