server:
  port: 8800

serverHost: 150.158.121.165

spring:
  application:
    name: dubbo-provider
  config:
    import:
      - nacos:dubbo-provider
  cloud:
    nacos:
      config:
        server-addr: ${serverHost}:8848
        namespace: springBootAgg
      discovery:
        server-addr: ${serverHost}:8848
        namespace: springBootAgg
#    sentinel:
#      datasource:
#        ds1:
#          nacos:
#            com.chat.server-addr: 150.158.121.165:8848
#            namespace: springBootAgg
#            group-id: DEFAULT_GROUP
#            dataId: dubbo-provider-flowRules
#            rule-type: flow

dubbo:
  application:
    name: dubbo-provider-dubbo
    qos-port: 33334
  protocol:
    name: dubbo
    port: 20883
  registry:
    address: nacos://${serverHost}:8848
    registerMode: instance
    #对应的分组名称
    group: DEFAULT_GROUP
    #对应的命名空间
    parameters:
      namespace: springBootAgg
  consumer:
    #启动不在是否有提供者,默认true如果没有则终止进程
    check: true
    #服务端如果返回超时(默认是1秒)会自动重试(默认是2秒)
    retries: 0

