server:
  port: 8801

serverHost: 150.158.121.165

spring:
  application:
    name: sentinelDemo
  config:
    import:
      - nacos:sentinelDemo
  cloud:
    nacos:
      config:
        server-addr: ${serverHost}:8848
        namespace: springBootAgg
      discovery:
        server-addr: ${serverHost}:8848
        namespace: springBootAgg
    sentinel:
      datasource:
        ds1:
          nacos:
            server-addr: 150.158.121.165:8848
            namespace: springBootAgg
            group-id: DEFAULT_GROUP
            dataId: sentinelDemo-flowRules
            rule-type: flow


dubbo:
  application:
    name: sentinelDemo-dubbo
    qos-port: 33333
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: nacos://${serverHost}:8848
    #对应的名称空间
    group: springBootAgg
  consumer:
    #启动不在是否有提供者,默认true如果没有则终止进程
    check: false
    #服务端如果返回超时(默认是1秒)会自动重试(默认是2秒)
    retries: 0


