#外部环境地址(云服务器地址)
extraEnvHost: hujingzheng.com

#设置项目名
server:
  servlet:
    context-path: /base-project
  port: 28081

#spring的相关配置
spring:
  application:
    name: base-project
  #===============数据库=================
  #spring-boot中对于@RestController或者@Controller+@ResponseBody注解的接口方法的返回值默认是Json格式，
  #对于date类型的数据，在返回浏览器端是会被spring-boot默认的Jackson框架转换，而Jackson框架默认的时区GMT（相对于中国是少了8小时）
  jackson:
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://${extraEnvHost}:3306/springBootDemo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&rewriteBatchedStatements=true
    username: ${jdbc.username}
    password: ${jdbc.pwd}
    driver-class-name: com.mysql.cj.jdbc.Driver
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  #本地缓存的配置
  cache:
    type: caffeine
    #该配置项在com.robben.config.CaffeineCacheConfig 也可以实现配置
#    cache-names:
#      - userCache
#    caffeine:
#      spec: maximumSize=1024,refreshAfterWrite=60s
  data:
    redis:
      host: ${extraEnvHost}
      port: 6379
      password: ${redis.pwd}

  cloud:
    nacos:
      config:
        server-addr: ${extraEnvHost}:38080
        group: DEFAULT_GROUP
        file-extension: properties
      discovery:
        server-addr: ${extraEnvHost}:38080

  config:
    import:
      - optional:nacos:base-project


link:
  name: adasdf
  msg: asdfasd22222


knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: false


#logging:
#  level:
#    com.robben: debug